from __future__ import annotations

"""Presentation-only UI-06 inspector alignment.

Reuses the existing TemplateInspector controls/signals/draft semantics. The
selected template gets a deterministic 16:9 preview generated by the same
fallback painter as gallery cards, while the original controls are rearranged
to match the approved UI-06 form without replacing any domain behavior.
"""

from PySide6.QtCore import QRectF, Qt
from PySide6.QtGui import QColor, QPainter, QPen
from PySide6.QtWidgets import QComboBox, QGridLayout, QHBoxLayout, QLabel, QVBoxLayout, QWidget

from .foundation_components import set_dynamic_property
from .foundation_icons import foundation_icon
from .post_release_template_card_adjustment import _paint_fallback

_installed = False


class TemplateInspectorPreview(QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.template_id = "spotify_clean"
        self.name = "Template"
        self.setMinimumHeight(145)
        self.setMaximumHeight(152)

    def set_template(self, template_id: str, name: str) -> None:
        self.template_id = str(template_id or "spotify_clean")
        self.name = str(name or "Template")
        self.update()

    def paintEvent(self, _event) -> None:
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
        outer = QRectF(self.rect()).adjusted(1, 1, -1, -1)
        painter.setPen(QPen(QColor("#D4DFEC"), 1))
        painter.setBrush(QColor("#0F1E31"))
        painter.drawRoundedRect(outer, 7, 7)
        inner = outer.adjusted(2, 2, -2, -2)
        painter.save()
        painter.setClipRect(inner)
        _paint_fallback(self, painter, inner)
        painter.restore()

        # Non-destructive preview chrome only; no playback state is fabricated.
        button = QRectF(inner.left() + 10, inner.bottom() - 30, 24, 20)
        painter.setBrush(QColor(8, 18, 31, 185))
        painter.setPen(Qt.PenStyle.NoPen)
        painter.drawRoundedRect(button, 4, 4)
        painter.setPen(QColor("#FFFFFF"))
        painter.drawText(button, Qt.AlignmentFlag.AlignCenter, "▶")
        painter.end()


def _clear_layout(layout) -> None:
    while layout.count():
        layout.takeAt(0)


def _field_row(label: str, control: QWidget, *, label_width: int = 94) -> QHBoxLayout:
    row = QHBoxLayout()
    row.setContentsMargins(0, 0, 0, 0)
    row.setSpacing(7)
    text = QLabel(label)
    text.setObjectName("metadata")
    text.setMinimumWidth(label_width)
    text.setMaximumWidth(label_width)
    row.addWidget(text)
    control.setMinimumHeight(30)
    control.setMaximumHeight(32)
    row.addWidget(control, 1)
    return row


def _set_combo_icon(combo: QComboBox, icon_name: str) -> None:
    icon = foundation_icon(icon_name, size=16)
    for index in range(combo.count()):
        combo.setItemIcon(index, icon)


def install_post_release_template_inspector_adjustment() -> None:
    global _installed
    if _installed:
        return

    from .template_workspace_step07 import TemplateInspector

    original_init = TemplateInspector.__init__
    original_set_template = TemplateInspector.set_template

    def compact_init(self, *args, **kwargs) -> None:
        original_init(self, *args, **kwargs)
        root = self.layout()
        if root is None:
            return

        # Preserve the recovered renderer contract/data value while matching the
        # UI-06 reference label shown to the user.
        if self.typography.count():
            self.typography.setItemText(0, "Playfair Display")

        # Preserve every production widget and its existing signal connection,
        # but discard the original vertical arrangement/label-only rows.
        _clear_layout(root)
        for child in self.findChildren(QLabel):
            if child is self.heading or child is self.identity or child is self.overlay_value:
                continue
            if child.parent() is self and child.text() in {
                "Title Layout", "Posisi Cover", "Background", "Spacing",
                "Tipografi", "Overlay Opacity", "Terapkan ke",
            }:
                child.hide()

        root.setContentsMargins(10, 8, 10, 8)
        root.setSpacing(5)

        self._post_template_preview = TemplateInspectorPreview(self)
        root.addWidget(self._post_template_preview)

        self.heading.setText("Pengaturan Template")
        self.heading.setStyleSheet(
            "font-size:15px;font-weight:700;color:#10234A;padding-top:6px;"
        )
        root.addWidget(self.heading)
        self.identity.hide()

        _set_combo_icon(self.title_layout, "template")
        _set_combo_icon(self.cover_position, "open")
        _set_combo_icon(self.background, "media")
        _set_combo_icon(self.spacing, "settings")
        _set_combo_icon(self.typography, "template")

        root.addLayout(_field_row("Title Layout", self.title_layout))
        root.addLayout(_field_row("Posisi Cover", self.cover_position))
        root.addLayout(_field_row("Background", self.background))
        root.addLayout(_field_row("Spacing", self.spacing))
        root.addLayout(_field_row("Tipografi", self.typography))

        opacity_row = QHBoxLayout()
        opacity_row.setContentsMargins(0, 0, 0, 0)
        opacity_row.setSpacing(7)
        opacity_label = QLabel("Opacity Overlay")
        opacity_label.setObjectName("metadata")
        opacity_label.setMinimumWidth(94)
        opacity_label.setMaximumWidth(94)
        opacity_row.addWidget(opacity_label)
        opacity_row.addWidget(self.overlay, 1)
        self.overlay_value.setMinimumWidth(38)
        opacity_row.addWidget(self.overlay_value)
        root.addLayout(opacity_row)

        # UI-06 shows the scope as its own section: heading first, then three
        # visible radio choices. Keep the production QComboBox as the state owner;
        # the density layer mirrors it with radio controls.
        self._post_template_scope_label = QLabel("Terapkan ke")
        self._post_template_scope_label.setObjectName("metadata")
        self._post_template_scope_label.setStyleSheet(
            "font-weight:600;color:#10234A;padding-top:3px;"
        )
        root.addWidget(self._post_template_scope_label)
        scope_row = QHBoxLayout()
        scope_row.setContentsMargins(0, 0, 0, 0)
        scope_row.setSpacing(8)
        scope_row.addWidget(self.scope, 1)
        root.addLayout(scope_row)
        self._post_template_scope_row = scope_row

        # Preview remains a live production control/signal but UI-06 presents the
        # selected preview through the preview canvas and global Preview command.
        # Keep the control instance for tests/automation while removing duplicate
        # visual chrome from this inspector.
        self.preview.hide()
        action_row = QHBoxLayout()
        action_row.setContentsMargins(0, 2, 0, 0)
        action_row.setSpacing(0)
        self.use.setMinimumHeight(34)
        self.use.setText("Gunakan Template")
        self.use.setIcon(foundation_icon("preview", color="#FFFFFF", size=16))
        action_row.addWidget(self.use, 1)
        root.addLayout(action_row)

        custom_row = QGridLayout()
        custom_row.setHorizontalSpacing(6)
        custom_row.setVerticalSpacing(5)
        set_dynamic_property(self.reset, "kind", "secondary")
        self.create.setIcon(foundation_icon("new", size=15))
        self.duplicate.setIcon(foundation_icon("template", size=15))
        self.save_custom.setIcon(foundation_icon("save", size=15))
        self.reset.setIcon(foundation_icon("undo", size=15))
        for button in (self.create, self.duplicate, self.save_custom, self.reset):
            button.setMinimumHeight(30)
            button.setMaximumHeight(32)
        custom_row.addWidget(self.create, 0, 0)
        custom_row.addWidget(self.duplicate, 0, 1)
        custom_row.addWidget(self.save_custom, 1, 0)
        custom_row.addWidget(self.reset, 1, 1)
        root.addLayout(custom_row)
        root.addStretch(1)

    def set_template_with_preview(self, descriptor, draft) -> None:
        original_set_template(self, descriptor, draft)
        preview = getattr(self, "_post_template_preview", None)
        if preview is not None:
            preview.set_template(descriptor.template_id, descriptor.name)
        # original_set_template writes the selected name into heading; restore
        # the UI-06 section heading while selection remains stored internally.
        self.heading.setText("Pengaturan Template")

    TemplateInspector.__init__ = compact_init
    TemplateInspector.set_template = set_template_with_preview
    _installed = True
